### ISSUE TITLE
Pi Desktop will not power up

### ISSUE THREAD

**Issue by robynjayqueerie** [hoopsurfer/pidesktop#23]
I have a pi desktop connected to a Pi3B also a 16GB SSD installed. All was working fine after some firmware updates earlier around the reboot, thank you
I left the unit powered up and running for a week or two, my plan is to leave it running permanently, will be part of a data collection system.
Noticed that the unit had failed, Pi was not running, LED on PiDesktop still on I think at that stage. On investigation Pi is OK, boots from a micro SD card and runs. I did get the SSD to work once so I think it is OK. Now just with the PiDesktop board on its own (no SSD attached) I have 5.5V coming in from the supply, the main switching power supply does not have its enable pin raised. Sometimes after leaving it unpowered for a while I can press the on button and the enable pin on the main supply comes on and everything powers up. Mostly nothing happens. Looking at the document on the way the power supply is organised, I suspect the micro which organises the power on/off process is confused or damaged.
Is there any clear path from here? I suspect I need to buy a new Pi Desktop but if there is an issue with them failing it will not suit what I want to use if for. Is there a circuit available which would allow us to see where the issue is? 
Thanks

**Comment by hoopsurfer** [comment]
From your description there are two things I would check carefully:

1) Make sure that your power adapter is rated 2.5-3A.  I have seen systems that are unreliable because of that issue.
2)  If you are running it standalone (with no Pi connected), you should be able to see it as a USB disk, 
3) If you press the power button and the LED lights then the power MCU should be working, it controls the LED (which is why I was able to make it flash on startup).

When you say everything powers up, do you see the rainbow boot screen?

**Comment by hoopsurfer** [comment]
This is very likely not to be an issue with the Pi Desktop software in this repos so closing this issue.
