### ISSUE TITLE
pinout

### ISSUE THREAD

**Issue by TiceRex** [hoopsurfer/pidesktop#26]
It's not an issue but I don't know how to ask questions...

Based on your experiences (and the source of the mcu program) could you be so kind to help us to sort this problem out: https://github.com/Gadgetoid/Pinout.xyz/issues/301 ?
Actually the problem's source is this page: https://github.com/pi-desktop/pi-desktop/blob/master/Pins-used-by-pi-desktop/Pins-used-by-pi-desktop.md
As far as I can see, these pins are in use only: GPIO6, 13 (MCU), and 2, 3 (i2c). What are the others (17, 19, 26) are doing? Are they in use at all?

Thank you in advance,
TiceRex

**Comment by hoopsurfer** [comment]
Here are the active pins and those intended for future use are indicated.  The MCUs use of I2C is not implemented and aside from sharing I2C pins, the RTC and MCU are not otherwise connected. I'm not sure what RTC_INT actually does, I haven't traced the board to the RTC to see where it is connected.

| GPIO   | Physical Pin | Function | Detail |
|---------|--------------|-----------|---------|
| GPIO2  | J8:2 | SDA |  I2C SDA for both RTC and MCU (future) |
| GPIO3  | J8:5| SCL |  I2C SCL for both RTC and MCU (future) |
| GPIO6 | J8:31 | PI RUN | Pi Running read by the MCU |
| GPIO13 | J8:33 | MCU Power | Pulse signal on shutdown from MCU to Pi |
| GPIO17 | J8:11 | RTC_INT | RTC interrupt signal (used?) |
| GPIO19 | J8:35 | MCU_RST | MCU reset (future) |
| GPIO26 | J8:37 | MCU_INT | MCU interrupt signal (future) |

**Comment by hoopsurfer** [comment]
This needs to be updated with info on RTC and future firmware updates so we will keep it open.

**Comment by TiceRex** [comment]
Thank you very much!

A query on i2c bus (i2cdetect -y 1) shows a device on address 0x18 (i2cdump shows zeros only). Is this the MCU?

The RTC (PCF8563) has an active low interrupt signal. Probably for normal (current) operation it's not in use, and in my understanding it should be used between the RTC and MCU only. In the future it can be used to wake up the MCU (and Pi) on schedule.
